#!/bin/bash

aws_account_id=$1
aws_role_name=$2

ASSUME_ROLE_OUTPUT=$(aws sts assume-role --role-arn arn:aws:iam::$aws_account_id:role/$aws_role_name --role-session-name $aws_role_name-$(date +%FT%H.%M.%S))
export AWS_ACCESS_KEY_ID=$(echo $ASSUME_ROLE_OUTPUT | jq --raw-output '.Credentials.AccessKeyId')
export AWS_SECRET_ACCESS_KEY=$(echo $ASSUME_ROLE_OUTPUT | jq --raw-output '.Credentials.SecretAccessKey')
export AWS_SESSION_TOKEN=$(echo $ASSUME_ROLE_OUTPUT | jq --raw-output '.Credentials.SessionToken')