#!/bin/bash

accountId=$1
roleName=$2
planFileName=$3
environment=$4
awsDefaultRegion=$5

terragruntDirectory="deploy/config/$environment/$awsDefaultRegion/lambda"

. deploy/bash/assume-role $accountId $roleName
deploy/bash/terragrunt-apply $terragruntDirectory $planFileName $awsDefaultRegion