#!/bin/bash

accountId=$1
roleName=$2
environment=$3
awsDefaultRegion=$4
component=$5
packageFileName=$6
planFileName=$7

terragruntDirectory="deploy/config/$environment/$awsDefaultRegion/$component"
currentDirectory=$(pwd)
lambdaZipPath="${currentDirectory}/${packageFileName}"

echo "Uploading file " + $packageFileName
printenv DOTNET_APP_VERSION
printenv NodeLambdaPackageFileName

. deploy/bash/assume-role $accountId $roleName
deploy/bash/terragrunt-plan $terragruntDirectory $planFileName $awsDefaultRegion $lambdaZipPath