deploy-us-east-1-dotnetlambda-dev:
  stage: deploy-dev
  variables:
    AwsDefaultRegion: us-east-1
    Environment: dev
    PlanFileName: 'dotnet-lambda-${AwsDefaultRegion}-${Environment}.tfplan'
    TerragruntDirectory: "deploy/config/${Environment}/${AwsDefaultRegion}/dotnet-lambda"
  extends: .terragrunt-apply-template
  dependencies:
    - build-dotnet
    - plan-us-east-1-dotnetlambda-dev
  only:
  - master
  - tags
  - web

deploy-us-west-1-dotnetlambda-dev:
  stage: deploy-dev
  variables:
    AwsDefaultRegion: us-west-1
    Environment: dev
    PlanFileName: 'dotnet-lambda-${AwsDefaultRegion}-${Environment}.tfplan'
    TerragruntDirectory: "deploy/config/${Environment}/${AwsDefaultRegion}/dotnet-lambda"
  extends: .terragrunt-apply-template
  dependencies:
    - build-dotnet
    - plan-us-west-1-dotnetlambda-dev
  only:
  - master
  - tags
  - web
